"""MediKiosk TTS service (plan T3.3, AD-2).

Serves build-time pre-baked mp3s keyed "<complaint>:<qid>:<lang>" from
services/tts/audio (generated by infra/scripts/bake_tts.py at image build).
Runtime /synthesize exists only for dynamic strings (confirmation echoes).
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, Response

app = FastAPI(title="MediKiosk TTS", version="0.1.0")

AUDIO_DIR = Path(os.getenv("TTS_AUDIO_DIR", "services/tts/audio"))
_cache: dict[str, bytes] = {}


@app.get("/healthz")
def healthz():
    return {"status": "ok", "service": "tts"}


@app.get("/tts/{key}.mp3")
def serve_baked(key: str):
    # manifest keys use ':'; on-disk filenames use '__' (Windows-safe)
    filename = key.replace(":", "__") + ".mp3"
    path = AUDIO_DIR / filename
    if not path.exists():
        raise HTTPException(404, f"no pre-baked audio for {key}")
    return FileResponse(path, media_type="audio/mpeg", filename=filename)


# --- runtime synthesis for dynamic strings (confirmation echoes) -----------

_VOICES = {"hi": "hi-IN-SwaraNeural", "en": "en-IN-NeerjaNeural"}


async def _synthesize(text: str, lang: str) -> bytes:
    import edge_tts

    voice = _VOICES.get(lang, _VOICES["en"])
    communicate = edge_tts.Communicate(text, voice)
    buf = b""
    async for ev in communicate.stream():
        if ev["type"] == "audio":
            buf += ev["data"]
    return buf


@app.get("/synthesize")
async def synth(text: str, lang: str = "hi"):
    """Dynamic strings; Redis LRU in prod — in-process hash cache for MVP."""
    cache_key = hashlib.sha1(f"{lang}:{text}".encode()).hexdigest()
    if cache_key in _cache:
        return Response(content=_cache[cache_key], media_type="audio/mpeg")
    backend = os.getenv("LANG_BACKEND", "edge")
    if backend == "bhashini":
        from medikiosk_tts.bhashini_backend import synthesize as bh_synthesize
        audio = bh_synthesize(text, lang=lang)
    else:
        audio = await _synthesize(text, lang)
    if len(_cache) > 500:
        _cache.clear()
    _cache[cache_key] = audio
    return Response(content=audio, media_type="audio/mpeg")